### ISSUE TITLE
Got issue in executing model.ipynb

### ISSUE THREAD

**Issue by puneethirvichetty** [Michigan10/Mouse_Contol_using_Hand_Gesture_Recognition_using_Deep_learning_CNN_in_Python#1]
NewRandomAccessFile failed to Create/Open: .\model\model.ckpt-41.data-00000-of-00001 : The system cannot find the file specified.
; No such file or directory
Sir, can you tell the detailed way of executing since there are many number of files.

![screenshot 40](https://user-images.githubusercontent.com/18632411/53285920-e8ab4b80-378c-11e9-904b-4303170b1dbc.png)
![screenshot 41](https://user-images.githubusercontent.com/18632411/53285921-ea750f00-378c-11e9-9c9a-901c5084434a.png)

**Comment by Praveendhouchak94** [comment]
Hi, puneethirvichetty
First you need to delete the model folder from the project folder. And then run the file again.

**Comment by Neeraj-singla** [comment]
Hi puneethirvichetty,
Firstly, you need to delete model from model folder then re-run main file again.
